version: '3.6'
services:
  server:
    build:
      context: apache
    container_name: sandbox-php
    working_dir: /var/www/sandbox
    volumes:
      - ../../../projects/kata-bootstraps/php:/var/www/sandbox
    ports:
      - 8123:80
